export const majorHistoryScores = [
  {
    schoolName: '中山大学',
    year: 2020,
    subjectType: 1,
    tier: 1,
    majorName: '财经学',
    minScore: 625,
    maxScore: 6668,
    targetProvince: '广东省',
    signedUpCount: 500,
    admittedCount: 223,
  },
  {
    schoolName: '中山大学',
    year: 2020,
    subjectType: 1,
    tier: 1,
    majorName: '法学',
    minScore: 611,
    maxScore: 649,
    targetProvince: '广东省',
    signedUpCount: 722,
    admittedCount: 433,
  },
  {
    schoolName: '中山大学',
    year: 2020,
    subjectType: 2,
    tier: 1,
    majorName: '应用物理学',
    minScore: 606,
    maxScore: 659,
    targetProvince: '广东省',
    signedUpCount: 755,
    admittedCount: 730,
  },
  {
    schoolName: '中山大学',
    year: 2020,
    subjectType: 2,
    tier: 1,
    majorName: '应用化学',
    minScore: 614,
    maxScore: 647,
    targetProvince: '广东省',
    signedUpCount: 722,
    admittedCount: 654,
  },
];
